name: env
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - imageio=2.22.0
  - opencv=4.6.0
  - tensorflow=2.9.1
  - tensorflow-base=2.9.1
  - tensorflow-deps=2.9.0
  - tensorflow-hub=0.12.0
  - pip:
      - numpy==1.23.4
      - pip==22.3.1
      - tensorflow-docs==0.0.0.dev0
      - tensorflow-macos==2.10.0
      - tensorflow-metal==0.6.0
